### ISSUE TITLE
响应状态码 | 一个计算机科学爱好者

### ISSUE THREAD

**Issue by ruoneo** [ruoneo/ruoneo-comment-repo#1]
http://124.220.165.92/2017/12/23/%E5%93%8D%E5%BA%94%E7%8A%B6%E6%80%81%E7%A0%81/ 

 一、状态码大类   状态码分类 说明    1xx 响应中——临时状态码，表示请求已经接受，告诉客户端应该继续请求或者如果它已经完成则忽略它   2xx 成功——表示请求已经被成功接收，处理已完成   3xx 重定向——重定向到其它地方：它让客户端再发起一个请求以完成整个处理。   4xx 客户端错误——处理发生错误，责任在客户端，如：客户端的请求一个不存在的资源，客户端未被授权，禁止访问等

**Comment by ruoneo** [comment]
test

**Comment by Markkkp** [comment]
> http://124.220.165.92/2017/12/23/%E5%93%8D%E5%BA%94%E7%8A%B6%E6%80%81%E7%A0%81/
> 
> 一、状态码大类 状态码分类 说明 1xx 响应中——临时状态码，表示请求已经接受，告诉客户端应该继续请求或者如果它已经完成则忽略它 2xx 成功——表示请求已经被成功接收，处理已完成 3xx 重定向——重定向到其它地方：它让客户端再发起一个请求以完成整个处理。 4xx 客户端错误——处理发生错误，责任在客户端，如：客户端的请求一个不存在的资源，客户端未被授权，禁止访问等



> http://124.220.165.92/2017/12/23/%E5%93%8D%E5%BA%94%E7%8A%B6%E6%80%81%E7%A0%81/
> 
> 一、状态码大类 状态码分类 说明 1xx 响应中——临时状态码，表示请求已经接受，告诉客户端应该继续请求或者如果它已经完成则忽略它 2xx 成功——表示请求已经被成功接收，处理已完成 3xx 重定向——重定向到其它地方：它让客户端再发起一个请求以完成整个处理。 4xx 客户端错误——处理发生错误，责任在客户端，如：客户端的请求一个不存在的资源，客户端未被授权，禁止访问

> test

你真棒！

**Comment by Markkkp** [comment]
> test

你是一个大聪明
